server { 
 listen 80;
 server_name frontend;
 root /usr/share/nginx/html;

 location ~ {
   try_files $uri $uri/ /webapp/index.html;
 }

 location /webapp {
   try_files $uri $uri/ /webapp/index.html;
 }

 location = /config.json {
   try_files $uri $uri/ /webapp/config.json;
 }

 location = /templates.json {
   try_files $uri $uri/ /webapp/templates.json;
 }

}